// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pikocloud/pikobrain/internal/ent/message"
	"github.com/pikocloud/pikobrain/internal/providers/types"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
}

// SetThread sets the "thread" field.
func (mc *MessageCreate) SetThread(s string) *MessageCreate {
	mc.mutation.SetThread(s)
	return mc
}

// SetToolName sets the "tool_name" field.
func (mc *MessageCreate) SetToolName(s string) *MessageCreate {
	mc.mutation.SetToolName(s)
	return mc
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (mc *MessageCreate) SetNillableToolName(s *string) *MessageCreate {
	if s != nil {
		mc.SetToolName(*s)
	}
	return mc
}

// SetToolID sets the "tool_id" field.
func (mc *MessageCreate) SetToolID(s string) *MessageCreate {
	mc.mutation.SetToolID(s)
	return mc
}

// SetNillableToolID sets the "tool_id" field if the given value is not nil.
func (mc *MessageCreate) SetNillableToolID(s *string) *MessageCreate {
	if s != nil {
		mc.SetToolID(*s)
	}
	return mc
}

// SetRole sets the "role" field.
func (mc *MessageCreate) SetRole(t types.Role) *MessageCreate {
	mc.mutation.SetRole(t)
	return mc
}

// SetUser sets the "user" field.
func (mc *MessageCreate) SetUser(s string) *MessageCreate {
	mc.mutation.SetUser(s)
	return mc
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (mc *MessageCreate) SetNillableUser(s *string) *MessageCreate {
	if s != nil {
		mc.SetUser(*s)
	}
	return mc
}

// SetMime sets the "mime" field.
func (mc *MessageCreate) SetMime(t types.MIME) *MessageCreate {
	mc.mutation.SetMime(t)
	return mc
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (mc *MessageCreate) SetNillableMime(t *types.MIME) *MessageCreate {
	if t != nil {
		mc.SetMime(*t)
	}
	return mc
}

// SetContent sets the "content" field.
func (mc *MessageCreate) SetContent(b []byte) *MessageCreate {
	mc.mutation.SetContent(b)
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MessageCreate) SetCreatedAt(t time.Time) *MessageCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MessageCreate) SetNillableCreatedAt(t *time.Time) *MessageCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetUpdatedAt sets the "updated_at" field.
func (mc *MessageCreate) SetUpdatedAt(t time.Time) *MessageCreate {
	mc.mutation.SetUpdatedAt(t)
	return mc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mc *MessageCreate) SetNillableUpdatedAt(t *time.Time) *MessageCreate {
	if t != nil {
		mc.SetUpdatedAt(*t)
	}
	return mc
}

// Mutation returns the MessageMutation object of the builder.
func (mc *MessageCreate) Mutation() *MessageMutation {
	return mc.mutation
}

// Save creates the Message in the database.
func (mc *MessageCreate) Save(ctx context.Context) (*Message, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MessageCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MessageCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MessageCreate) defaults() {
	if _, ok := mc.mutation.Mime(); !ok {
		v := message.DefaultMime
		mc.mutation.SetMime(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := message.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		v := message.DefaultUpdatedAt()
		mc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MessageCreate) check() error {
	if _, ok := mc.mutation.Thread(); !ok {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required field "Message.thread"`)}
	}
	if _, ok := mc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Message.role"`)}
	}
	if v, ok := mc.mutation.Role(); ok {
		if err := message.RoleValidator(string(v)); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Mime(); !ok {
		return &ValidationError{Name: "mime", err: errors.New(`ent: missing required field "Message.mime"`)}
	}
	if v, ok := mc.mutation.Mime(); ok {
		if err := message.MimeValidator(string(v)); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf(`ent: validator failed for field "Message.mime": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Message.content"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Message.created_at"`)}
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Message.updated_at"`)}
	}
	return nil
}

func (mc *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.Thread(); ok {
		_spec.SetField(message.FieldThread, field.TypeString, value)
		_node.Thread = value
	}
	if value, ok := mc.mutation.ToolName(); ok {
		_spec.SetField(message.FieldToolName, field.TypeString, value)
		_node.ToolName = value
	}
	if value, ok := mc.mutation.ToolID(); ok {
		_spec.SetField(message.FieldToolID, field.TypeString, value)
		_node.ToolID = value
	}
	if value, ok := mc.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := mc.mutation.User(); ok {
		_spec.SetField(message.FieldUser, field.TypeString, value)
		_node.User = value
	}
	if value, ok := mc.mutation.Mime(); ok {
		_spec.SetField(message.FieldMime, field.TypeString, value)
		_node.Mime = value
	}
	if value, ok := mc.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeBytes, value)
		_node.Content = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
}

// Save creates the Message entities in the database.
func (mcb *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Message, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
