// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/pikocloud/pikobrain/internal/ent/message"
	"github.com/pikocloud/pikobrain/internal/ent/schema"
	"github.com/pikocloud/pikobrain/internal/providers/types"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescRole is the schema descriptor for role field.
	messageDescRole := messageFields[3].Descriptor()
	// message.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	message.RoleValidator = messageDescRole.Validators[0].(func(string) error)
	// messageDescMime is the schema descriptor for mime field.
	messageDescMime := messageFields[5].Descriptor()
	// message.DefaultMime holds the default value on creation for the mime field.
	message.DefaultMime = types.MIME(messageDescMime.Default.(string))
	// message.MimeValidator is a validator for the "mime" field. It is called by the builders before save.
	message.MimeValidator = messageDescMime.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[7].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageFields[8].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
}
